### ISSUE TITLE
Add support for log_likelihood to semisupervised_classification.iterative_labeling.AutonBox primitive

### ISSUE THREAD

**Issue by roquelopez** [autonlab/autonbox#9]
`iterative_labeling`  is a powerful and useful primitive. We used it on text semi-supervised problems. I think would be very nice to have `log_likelihood` implemented in `iterative_labeling` primitive. I think the implementation should be simple since it just has to use the log_likelihood  method of the classifiers. Do you think it is doable? Thanks!

**Comment by saswatiray** [comment]
We are looking into this!

**Comment by saswatiray** [comment]
Fixed. This will need some change in log_likelihoods() functions of the estimators to be able to handle data with unlabeled classes.
